---
- name: Install LAMMPS dependencies
  become: true
  become_user: "{{ root_user }}"
  apt:
      name: "{{ item }}"
      state: latest
  with_items:
    - build-essential
    - gfortran
    - gcc
    - libblas-dev 
    - liblapack-dev
    - openmpi-bin

- name: Get LAMMPS from github
  git:
     repo: https://github.com/lammps/lammps.git
     dest: "{{ lammps_root_dir}}"


- name: Make LAMMPS
  make: 
    chdir: "{{ lammps_root_dir }}/src/"
    target: "{{ item }}"
  with_items:
      - yes-CLASS2
      - yes-KSPACE
      - yes-MANYBODY
      - yes-MISC
      - yes-MOLECULE
      - yes-REPLICA
      - yes-RIGID
      - yes-USER-MISC
      - serial

- name: "Put a line in ~/.profile to add LAMMPS to the path"
  lineinfile:
    path: "${HOME}/.profile"
    line: "export PATH=${PATH}:{{ lammps_root_dir }}/src/"

