---
- name: Install LAMMPS dependencies
  become: true
  apt:
    name:
      - build-essential
      - gfortran
      - gcc
      - libblas-dev
      - liblapack-dev
      - openmpi-bin

- name: Get LAMMPS from github
  git:
    repo: https://github.com/lammps/lammps.git
    dest: "{{ lammps_root_dir }}"
    version: "{{ lammps_version }}"
    depth: 1
  register: git_checkout

- name: Make LAMMPS
  make:
    chdir: "{{ lammps_root_dir }}/src/"
    target: "{{ item }}"
  with_items:
    - yes-CLASS2
    - yes-KSPACE
    - yes-MANYBODY
    - yes-MISC
    - yes-MOLECULE
    - yes-REPLICA
    - yes-RIGID
    - yes-USER-MISC
    - serial
  when: git_checkout.changed

- name: "Put a line in ~/.profile to add LAMMPS to the path"
  lineinfile:
    path: "${HOME}/.profile"
    line: "export PATH=${PATH}:{{ lammps_root_dir }}/src/"
